version: '3'
name: 'personal'

services:
  cybersyn_takehome:
    container_name: cybersyn_takehome
    network_mode: host
    build:
      context: ../../
      dockerfile: .devcontainer/.dev_environment/Dockerfile

    # docker run -it
    stdin_open: true
    tty: true

    ports:
      - "6789:6789"

    volumes:
      - ../../:/cybersyn_takehome
      - ~/.dbt/profiles.yml:/root/.dbt/profiles.yml

    user: root
